name: Deploy the example app to GitHub Pages
on: [workflow_dispatch, workflow_call]

env:
  package_dir: ./
  example_dir: ./example
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        working-directory: ${{ env.example_dir }}
        run: flutter pub get

      - name: Build web app
        working-directory: ${{ env.example_dir }}
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.example_dir }}/build/web
